# Generated by Django 3.1.5 on 2021-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_createaccount_acctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='accno',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='phonenumber',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
